### ISSUE TITLE
[PATCH /user/profilePicture] In /user/profilePicture response 500 Internal Server Error - always

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#289]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/profilePicture
3. Click on 'Try out'
4. Enter valid params  

**Actual result**
Response 500 Internal Server Error

**Expected result**
Response 200 OK

**Comment by nklimovych** [comment]
In this task, the main challenge was to configure environment variables and connect to Azure cloud storage. I created a new Azure account, then created a new storage account and container. After that I added a connection string to the environment variables.
When I checked if everything worked, the file was sent to the container, the response code was 200 (OK). Just as this issue requires.
