### ISSUE TITLE
[PATCH /user/profilePicture] In /user/profilePicture need response 401 Unauthorized

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#290]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/profilePicture
3. Click on 'Try out'
4. Enter valid params  

**Actual result**
Response 500 Internal Server Error

**Expected result**
Response 401 Unauthorized

**Comment by nklimovych** [comment]
This issue was fixed earlier, so there is no need to make any changes
