### ISSUE TITLE
Create unit test to package Mapping

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#300]
Create unit test to GreenCityMVP service/src/main/java/greencity/mapping

1. - [ ] CategoryDtoMapper
2.  - [ ] CategoryDtoResponseMapper
3. - [ ] CustomHabitMapper
4. - [ ] CustomShoppingListMapper
5. - [ ] CustomShoppingListResponseDtoMapper
6. - [ ] EcoNewsAuthorDtoMapper
7. - [ ] EcoNewsCommentDtoMapper
8. - [ ] EcoNewsCommentVOMapper
9. - [ ] EcoNewsDtoMapper
10. - [ ] EcoNewsVOMapper
11. - [ ] FilterDtoRequestMapper
12. - [ ] FilterDtoResponseMapper
13. - [ ] HabitAssignDtoMapper
14. - [ ] HabitAssignManagementDtoMapper
15. - [ ] HabitAssignMapper
16. - [ ] HabitAssignUserDurationDtoMapper
17. - [ ] HabitDtoMapper
18. - [ ] HabitFactDtoResponseMapper
19. - [ ] HabitManagementDtoMapper
20. - [ ] HabitStatisticDtoMapper
21. - [ ] HabitStatusCalendarMapper
22. - [ ] HabitStatusCalendarVOMapper
23. - [ ] HabitTranslationDtoMapper
24. - [ ] HabitTranslationMapper
25. - [ ] LanguageTranslationDtoMapper
26. - [ ] MultipartBase64ImageMapper
27. - [ ] NewTagDtoMapper
28. - [ ] SearchNewsDtoMapper
29. - [ ] ShoppingListItemDtoMapper
30. - [ ] ShoppingListItemRequestDtoMapper
31. - [ ] ShoppingListItemResponseDtoMapper
32. - [ ] ShoppingListItemWithStatusRequestDtoMapper
33. - [ ] TagDtoMapper
34. - [ ] TagMapper
35. - [ ] TagVOMapper
36. - [ ] UtilsMapper

**Acceptance Criteria:**

* All tests pass successfully.
* The code is clean and adheres to coding standards.
* Dependencies are correctly mocked, and their methods are verified for calls.
* Test coverage should be 100%.

**Comment by arthurmkrtchian** [comment]
**In progress**

@arthurmkrtchian 
- [x] 1. CategoryDtoMapper
- [x] 2. CategoryDtoResponseMapper
- [x] 3. CustomHabitMapper
- [x] 4. CustomShoppingListMapper
- [x] 5. CustomShoppingListResponseDtoMapper

@YuliaPylypenko 
- [x] 6. EcoNewsAuthorDtoMapper
- [x] 7. EcoNewsCommentDtoMapper
- [x] 8. EcoNewsCommentVOMapper
- [x] 9. EcoNewsDtoMapper
- [x] 10. EcoNewsVOMapper

@VladyslavSiverskiy 
- [x] 11. FilterDtoRequestMapper
- [x] 12. FilterDtoResponseMapper
- [x] 13. HabitAssignDtoMapper
- [x] 14. HabitAssignManagementDtoMapper
- [x] 15. HabitAssignMapper

@nklimovych 
- [x] 16. HabitAssignUserDurationDtoMapper
- [x] 17. HabitDtoMapper
- [x] 18. HabitFactDtoResponseMapper
- [x] 19. HabitManagementDtoMapper
- [x] 20. HabitStatisticDtoMapper

@otulush 
- [x]  21. HabitStatusCalendarMapper
- [x]  22. HabitStatusCalendarVOMapper
- [x]  23. HabitTranslationDtoMapper
- [x]  24. HabitTranslationMapper
- [x]  25. LanguageTranslationDtoMapper

@MaksymFartushok 
- [x]  26. MultipartBase64ImageMapper
- [x]  27. NewTagDtoMapper
- [x]  28. SearchNewsDtoMapper
- [x]  29. ShoppingListItemDtoMapper
- [x]  30. ShoppingListItemRequestDtoMapper

@arthurmkrtchian 
- [x] 31. ShoppingListItemResponseDtoMapper
- [x] 32. ShoppingListItemWithStatusRequestDtoMapper
- [x] 33. TagDtoMapper
- [x] 34. TagMapper
- [x] 35. TagVOMapper
- [x] 36. UtilsMapper

**Comment by YuliaPylypenko** [comment]
So, i'll take the next five.

@YuliaPylypenko 
6-10 (inclusive).

**Comment by VladyslavSiverskiy** [comment]
I'll take the next five

@VladyslavSiverskiy
11-15 (inclusive).

**Comment by arthurmkrtchian** [comment]
-

**Comment by nklimovych** [comment]
I'll take next 5 (16-20)

**Comment by otulush** [comment]
I'll take next 5 (21-25)

**Comment by MaksymFartushok** [comment]
I'll take next 5 (26-30)

**Comment by arthurmkrtchian** [comment]
I'll take the remaining 6 (31-36)
