### ISSUE TITLE
[PUT /user/updateUserLastActivityTime/{date}] In /user/updateUserLastActivityTime/{date} response 401 Unauthorized - need 403 Forbidden

### ISSUE THREAD

**Issue by GreenCity23** [GreenCity23/GreenCityProject#316]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us user
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PUT /user/updateUserLastActivityTime/{date}
3. Click on 'Try out'
4. Enter valid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 403 Forbidden

**Comment by otulush** [comment]
Nothing to fix. Everything works as expected.
